### ISSUE TITLE
start to finish instructions would be greatly appreciated

### ISSUE THREAD

**Issue by FuzzyWobble** [thmoa/videoavatars#1]
Hello. Some start to finish instructions would be greatly appreciated. Such as, how do we generate a masks.hdf5 and keypoints.hdf5 and reconstructed_poses.pkl and camera.pkl ? All these are needed in step 1. Thanks :)

**Comment by rampagedog12** [comment]
OSVOS -> mask
Openpose -> keypoints
The other two I am not sure. Keep testing......

**Comment by thmoa** [comment]
It should be reconstructed_poses.hdf. Fixed that in 56d980b. Anyway, it is coming pre-computed in the dataset.
Add a helper for camera.pkl in f5b8616.

**Comment by ErfolgreichCharismatisch** [comment]
Agreed. Please elaborate on how to use your piece of software.

**Comment by ErfolgreichCharismatisch** [comment]
"OSVOS -> mask"

How?

**Comment by rampagedog12** [comment]
@ErfolgreichCharismatisch 
Google OSVOS DAVIS and you will find the paper and software.
OSVOS is also metioned in videoavatars' paper.

**Comment by ErfolgreichCharismatisch** [comment]
@rampagedog12 I did. But the software makes no sense as it doesn't have pictures as input and masks as output but requires pictures as input and masks as input.

Also https://graphics.tu-bs.de/upload/publications/alldieck2018videopeople.pdf does not contain the term OSVOS once.

**Comment by rampagedog12** [comment]
@ErfolgreichCharismatisch They mention OSVOS in Reference 9. One shot video object segmentation. To use OSVOS, You need to spend time on reading the paper and the codes. The documentation is not clear for me, too. It cost me 2-3 days to learn to run it. So does videoavatars. Though it works, there are some restrictions and the performance is not as good as I think. More time is spent on learning deeper on the tool. However, they are good tools. I enjoy learning them.
OSVOS requires a sequence of pictures and a ground truth mask of the first picture as input. Run the online training, it will create a new model using its trained model and your new data. Then, it will run the test and you will get the masks.

**Comment by ErfolgreichCharismatisch** [comment]
@rampagedog12 This will go offtopic: You wrote "It cost me 2-3 days to learn to run it" and this made me think. I often did that with various computer tasks. Sitting in front of my computer and trying to make a software run. Just to then have it run and think: "meh and this is what I spent two days of my life for?". Now what would happen if I couldn't run the software? Nothing really. Do I need it? Definitely not. So why not just stop right there and focus on something useful, I think.

**Comment by rampagedog12** [comment]
@ErfolgreichCharismatisch True. Just focusing on something else is not a bad idea. Touching a software in a right time is a good ability. With the previous users' experience and the completed official instruction, you could spend few min learning how to run it and figure out whether it is useful.

**Comment by FuzzyWobble** [comment]
Is anyone able to provide documentation for this? 
It's sad to let such a great project be crippled by the lack of documentation...

**Comment by shanYanGuan** [comment]
@rampagedog12 openpose to dectect 2d or 3d points?

**Comment by shanYanGuan** [comment]
seems that one frame have 54 values, that means, there have 18 3d points?

**Comment by shanYanGuan** [comment]
okay... I found the answear... openpose output(x,y,c),so it detect 2d points

**Comment by naren142** [comment]
@mehameha998 How to get the 54 values?
