### ISSUE TITLE
which part is to render texture image to body model?

### ISSUE THREAD

**Issue by shanYanGuan** [thmoa/videoavatars#10]
Hello, I scanned your code, while It seems thatI didn't get your ticket to render texture image but generate texture image.

**Comment by shanYanGuan** [comment]
By the way, could you please confirm my request for your dataset?  Thanks very much!

**Comment by thmoa** [comment]
Code for texture generation and mesh texture coordinates are provided.
Rendering is then straight-forward. Use your own code or professional tools like Blender or Maya.

**Comment by shanYanGuan** [comment]
Thank you so much! I have overcome it!

**Comment by salmedina** [comment]
> Thank you so much! I have overcome it!

How did you solve adding the texture to the SMPL model?
