### ISSUE TITLE
How to compute 'vt' and 'ft'?

### ISSUE THREAD

**Issue by shanYanGuan** [thmoa/videoavatars#11]
hello @thmoa ,Could you tell me how to compute 'basicModel_vt' &'basicModel_ft' by my self?

**Comment by thmoa** [comment]
This is not an issue related to this software.

The texture coordinates do not need to be recomputed - they are shared between all models.
https://en.wikipedia.org/wiki/UV_mapping

**Comment by Frank-Dz** [comment]
> hello @thmoa ,Could you tell me how to compute 'basicModel_vt' &'basicModel_ft' by my self?

@shyanguan Hi~ Is it possible to contact you via email to have a discussion about setting up the code? I tried to find your email address, but I did not find it.
