### ISSUE TITLE
The code of frame refinement  is lacked?

### ISSUE THREAD

**Issue by shanYanGuan** [thmoa/videoavatars#12]
Step3 have two works, one of which is to get time varying details. But It seems that your code in github doesn't contain this work. 

Moreover, could you tell me how to get KinectCap's dataset?

Thanks! @thmoa

**Comment by thmoa** [comment]
The time-varying details are not included in the code for simplicity. It is very similar to the consensus estimation.
The KinectCap dataset is not public and has to be requested from the authors.
