### ISSUE TITLE
How to render the SMPL model with texture

### ISSUE THREAD

**Issue by HuntleyZ** [thmoa/videoavatars#13]
Hello @thmoa ,
     I've already got the personalized SMPL model and its corresponding texture map. I am using 
`rn = ColoredRenderer()` and `rn.set(texture_image=my_texture_img)` but it seems that it's not working. I'm wondering how to generate the result image that is the same as the generated images in your demo. Many thanks!

**Comment by thmoa** [comment]
Please have a look at the OpenDR documentation to see how to render with texture. You can use any other rendering tool of your choice, too.

The ColoredRenderer can't renderer a texture. Use the TexturedRenderer.
This might help: https://github.com/mattloper/opendr/wiki/Simple-Optimization

**Comment by shanYanGuan** [comment]
Hi,@HuntleyZ 
Have you find the answer?
