### ISSUE TITLE
request for the datasets has been refuse

### ISSUE THREAD

**Issue by yuli1994** [thmoa/videoavatars#14]
Hi,Appreciate your work so much,then I'm trying get the dataset ,I got this reply:
SMTP error, RCPT TO: 550-sender envelope address ``````` is locally blacklisted here. If
550 you think this is wrong, get in touch with postmaster
please tell me why ,waiting for your answer. thanks

**Comment by thmoa** [comment]
Hi,
I talked to our sysadmin. Apparently, we get much spam from @163.com - so it is blacklisted. We whitelisted your email now. Please send your request again and consider to use your university address next time.

**Comment by yuli1994** [comment]
@thmoa 
Thank you! Problem solved.I'm gonna use my university address next time.
