### ISSUE TITLE
ValueError , run step2_consensus.py 

### ISSUE THREAD

**Issue by yuli1994** [thmoa/videoavatars#15]
Hi,
   when I run step2_consensus.py,It running to Step 0,Matching rays with contours,and stopped at 2%.

> Exception KeyError: KeyError(<weakref at 0x2abbc65a99f0; to 'tqdm' at 0x2abbc3d59690>,) in  ignored
Traceback (most recent call last):
  File "step2_consensus.py", line 204, in <module>
    args.first_frame, args.last_frame, args.nohands, args.naked, args.display)
  File "step2_consensus.py", line 133, in main
    fit_consensus(frames, base_smpl, camera, frustum, model_data, nohands, icp_count, naked, display)
  File "step2_consensus.py", line 82, in fit_consensus
    E['silh_{}'.format(current)] = ray_objective(f, sigma, base_smpl, camera, vis_rn_b, vis_rn_m)
  File "/home/liudongbo/yuli/videoavatars/lib/rays.py", line 93, in ray_objective
    f.v_ids, f.rays_u = unpose_and_select_rays(f.rays, f.Vi, base_smpl, vis_rn_b, vis_rn_m)
  File "/home/liudongbo/yuli/videoavatars/lib/rays.py", line 33, in unpose_and_select_rays
    ray_matches = np.argmin(dist, axis=0)
  File "/usr/local/lib/python2.7/dist-packages/numpy-1.15.1-py2.7-linux-x86_64.egg/numpy/core/fromnumeric.py", line 1101, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "/usr/local/lib/python2.7/dist-packages/numpy-1.15.1-py2.7-linux-x86_64.egg/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence

I trace back to the lib/geometry.py,and found :
('visible:', array([], dtype=int64)), in function "visible_boundary_edges" at line 9,It's empty.
and here it's my mask data and keypoints json:
![image-3124](https://user-images.githubusercontent.com/26033422/45290347-f6904b80-b521-11e8-8179-220a5a4c461e.png)
{"image_id": "./data/image-31.jpeg", "category_id": 1, "keypoints": [316, 144, 2, 324, 134, 2, 304, 134, 2, 338, 138, 2, 290, 140, 2, 354, 196, 2, 312, 196, 2, 268, 196, 2, 402, 248, 2, 216, 248, 2, 446, 302, 2, 158, 300, 2, 346, 340, 2, 286, 340, 2, 358, 458, 2, 288, 452, 2, 360, 550, 2, 294, 552, 2], "score": 1.536439299583435}
It bother me two days! feel so sorry to bother you.
Thanks a lot.

**Comment by thmoa** [comment]
This is not an issue with the software. Please debug your code. No vertices are in the view frustum.

**Comment by void-main** [comment]
I got the same error here. I haven't modified any code, just running the code with my own examples. I know that the vertices are empty but I don't know why. Any tips on how to debug this issue? Is it because the camera parameters are bad or I missed some steps?

**Comment by lyupei** [comment]
same issue.

**Comment by ischansgithub** [comment]
> Hi,
> when I run step2_consensus.py,It running to Step 0,Matching rays with contours,and stopped at 2%.
> 
> > Exception KeyError: KeyError(<weakref at 0x2abbc65a99f0; to 'tqdm' at 0x2abbc3d59690>,) in  ignored
> > Traceback (most recent call last):
> > File "step2_consensus.py", line 204, in 
> > args.first_frame, args.last_frame, args.nohands, args.naked, args.display)
> > File "step2_consensus.py", line 133, in main
> > fit_consensus(frames, base_smpl, camera, frustum, model_data, nohands, icp_count, naked, display)
> > File "step2_consensus.py", line 82, in fit_consensus
> > E['silh_{}'.format(current)] = ray_objective(f, sigma, base_smpl, camera, vis_rn_b, vis_rn_m)
> > File "/home/liudongbo/yuli/videoavatars/lib/rays.py", line 93, in ray_objective
> > f.v_ids, f.rays_u = unpose_and_select_rays(f.rays, f.Vi, base_smpl, vis_rn_b, vis_rn_m)
> > File "/home/liudongbo/yuli/videoavatars/lib/rays.py", line 33, in unpose_and_select_rays
> > ray_matches = np.argmin(dist, axis=0)
> > File "/usr/local/lib/python2.7/dist-packages/numpy-1.15.1-py2.7-linux-x86_64.egg/numpy/core/fromnumeric.py", line 1101, in argmin
> > return _wrapfunc(a, 'argmin', axis=axis, out=out)
> > File "/usr/local/lib/python2.7/dist-packages/numpy-1.15.1-py2.7-linux-x86_64.egg/numpy/core/fromnumeric.py", line 51, in _wrapfunc
> > return getattr(obj, method)(*args, **kwds)
> > ValueError: attempt to get argmin of an empty sequence
> 
> I trace back to the lib/geometry.py,and found :
> ('visible:', array([], dtype=int64)), in function "visible_boundary_edges" at line 9,It's empty.
> and here it's my mask data and keypoints json:
> ![image-3124](https://user-images.githubusercontent.com/26033422/45290347-f6904b80-b521-11e8-8179-220a5a4c461e.png)
> {"image_id": "./data/image-31.jpeg", "category_id": 1, "keypoints": [316, 144, 2, 324, 134, 2, 304, 134, 2, 338, 138, 2, 290, 140, 2, 354, 196, 2, 312, 196, 2, 268, 196, 2, 402, 248, 2, 216, 248, 2, 446, 302, 2, 158, 300, 2, 346, 340, 2, 286, 340, 2, 358, 458, 2, 288, 452, 2, 360, 550, 2, 294, 552, 2], "score": 1.536439299583435}
> It bother me two days! feel so sorry to bother you.
> Thanks a lot.
#################################################################################
Hi,Adarine,Have you solved it? I got same issue.would you please help me?

**Comment by ischansgithub** [comment]
> I got the same error here. I haven't modified any code, just running the code with my own examples. I know that the vertices are empty but I don't know why. Any tips on how to debug this issue? Is it because the camera parameters are bad or I missed some steps?
#################################################################################

Hi,void-main ,Have you solved it? I got same issue.would you please help me?

**Comment by ischansgithub** [comment]
> same issue.

Hi,lyupei.  Have you solve it?

**Comment by timctran** [comment]
I also ran into this problem. In my case, I determined that the `reconstructed_poses.hdf5` file was at fault.

Here's some code to quickly debug your poses file:

    import h5py
    import numpy as np

    poses = h5py.File("reconstructed_poses.hdf5")['pose']
    n = len(poses)
    print("Number of frames:", n)
    print("Number of nontrivial poses:", len([x for x in poses if np.sum(x) != 0]))

In my case, I had a poses file with 757 frames but 0 nontrivial poses (every frame was an array filled with 0s).

**Comment by fasogbon** [comment]
Anybody solved this issue!
The code used to work on a different virtual environment i had but i made some unknown updates and it stopped working and giving this error.
Any help from you guys will save my day

**Comment by fasogbon** [comment]
Problem solved-

1. Dont use latest pip, or
2.Use  opencv-python (3.*) versions instead of 4

**Comment by enric1994** [comment]
Why is this issue closed? Everybody is having exactly the same error and there is no solution.
See attached the keypoints/masks/reconstruction I am trying to use for step 2.
I am using the Docker environment provided by https://github.com/Kurotsuba/CVProjectVideoAvatar

I suspect that my problem is that the masks are not accurate enough or they don't match with the camera configuration, however the step 1 spend almost one day on my machine so it's very slow to debug.

[data.zip](https://github.com/thmoa/videoavatars/files/3921540/data.zip)

**Comment by zhumorui** [comment]
> Why is this issue closed? Everybody is having exactly the same error and there is no solution.
> See attached the keypoints/masks/reconstruction I am trying to use for step 2.
> I am using the Docker environment provided by https://github.com/Kurotsuba/CVProjectVideoAvatar
> 
> @fasogbon the issue is not OpenCV for me, I can run step 2 on the sample files but not using the ones I generated.
> 
> I suspect that my problem is that the masks are not accurate enough or they don't match with the camera configuration, however the step 1 spend almost one day on my machine so it's very slow to debug.
> 
> [data.zip](https://github.com/thmoa/videoavatars/files/3921540/data.zip)

Hello,Have you solved this problem?
