### ISSUE TITLE
Could you tell me how to caculate camera parameters?

### ISSUE THREAD

**Issue by shanYanGuan** [thmoa/videoavatars#17]
I am trying your code in Human 3.6M, but I don't know how to set camera parameters. And camera parameters make difference a lot in results.
I have read your code about camera, but what 'f' should be setted?

**Comment by thmoa** [comment]
f is the focal length. Please refer to https://github.com/mattloper/opendr/wiki

**Comment by shanYanGuan** [comment]
I know this. But i don't know how to estimate image's focal length. Could you give me a hint about how to get focal length from one image?
