### ISSUE TITLE
Is there any example input data?

### ISSUE THREAD

**Issue by firstmover** [thmoa/videoavatars#18]
Hi, thanks for sharing the code. I really want to follow your work and try to use the code in this project. But I found it difficult to understand and modify it since there is not any example input data or related instruction except what is in "Usage". Is is possible to get some data you used? For example, an input video and the corresponding smpl output would be great. Thanks.

**Comment by thmoa** [comment]
Dataset: https://graphics.tu-bs.de/people-snapshot

**Comment by thmoa** [comment]
Dataset: https://graphics.tu-bs.de/people-snapshot

**Comment by thmoa** [comment]
Dataset: https://graphics.tu-bs.de/people-snapshot
