### ISSUE TITLE
cv2.error in step2_consensus

### ISSUE THREAD

**Issue by Vova-B** [thmoa/videoavatars#19]
When I start step2_consensus.py an error occurs cv2.error: OpenCV(3.4.3) /io/opencv/modules/calib3d/src/calibration.cpp:550: error: (-5:Bad argument) One of required arguments is not a valid matrix in function 'cvProjectPoints2'

**Comment by thmoa** [comment]
You probably input wrong camera parameters. This message is not helpful at all.

**Comment by Vova-B** [comment]
> You probably input wrong camera parameters. This message is not helpful at all.

This error occurs with any parameters for the camera.

**Comment by thmoa** [comment]
Then please check if your OpenCV version is compatible with OpenDR -- OpenDR is not part of my project. I never experienced this issue...

**Comment by Vova-B** [comment]
Tell me which version of OpenCV did you use?

**Comment by thmoa** [comment]
3.4.1

Check the OpenDR examples, to verify.

**Comment by Vova-B** [comment]
Opendr examples run and work. I'll try to install your opencv version

**Comment by Vova-B** [comment]
I tried to change versions, reinstall libraries, I still get this error.
`OpenCV(3.4.1) Error: Assertion failed ((((_src) != __null && (((const CvMat*)(_src))->type & 0xFFFF0000) == 0x42420
000 && ((const CvMat*)(_src))->cols > 0 && ((const CvMat*)(_src))->rows > 0) && ((const CvMat*)(_src))->data.ptr !=
 __null) && (((_dst) != __null && (((const CvMat*)(_dst))->type & 0xFFFF0000) == 0x42420000 && ((const CvMat*)(_dst
))->cols > 0 && ((const CvMat*)(_dst))->rows > 0) && ((const CvMat*)(_dst))->data.ptr != __null) && (_src->rows == 
1 || _src->cols == 1) && (_dst->rows == 1 || _dst->cols == 1) && _src->cols + _src->rows - 1 == _dst->rows + _dst->
cols - 1 && (((_src->type) & ((1 << 3)*512 - 1)) == (((5) & ((1 << 3) - 1)) + (((2)-1) << 3)) || ((_src->type) & ((
1 << 3)*512 - 1)) == (((6) & ((1 << 3) - 1)) + (((2)-1) << 3))) && (((_dst->type) & ((1 << 3)*512 - 1)) == (((5) & 
((1 << 3) - 1)) + (((2)-1) << 3)) || ((_dst->type) & ((1 << 3)*512 - 1)) == (((6) & ((1 << 3) - 1)) + (((2)-1) << 3
)))) in cvUndistortPointsInternal, file /io/opencv/modules/imgproc/src/undistort.cpp, line 384
OpenCV(3.4.1) Error: Bad argument (One of required arguments is not a valid matrix) in cvProjectPoints2, file /io/o
pencv/modules/calib3d/src/calibration.cpp, line 550
Traceback (most recent call last):
  File "step2_consensus.py", line 203, in <module>
    args.first_frame, args.last_frame, args.nohands, args.naked, args.display)
  File "step2_consensus.py", line 128, in main
    frames.append(setup_frame_rays(base_smpl, camera, camera_t, camera_rt, pose_i, trans_i, mask))
  File "/home/vbogdan1898/Realistic3DHumanModel/lib/frame.py", line 46, in setup_frame_rays
    f.rays = rays_from_silh(f.mask, camera)
  File "/home/vbogdan1898/Realistic3DHumanModel/lib/rays.py", line 86, in rays_from_silh
    rays = rays_from_points(points, camera)
  File "/home/vbogdan1898/Realistic3DHumanModel/lib/rays.py", line 66, in rays_from_points
    points3d = camera.unproject_points(points)
  File "/home/vbogdan1898/.local/lib/python2.7/site-packages/opendr/camera.py", line 120, in unproject_points
    ch.minimize(cam - uvd, x0=[cam.v], method='dogleg', options={'disp': 0})
  File "/home/vbogdan1898/.local/lib/python2.7/site-packages/chumpy/optimization.py", line 41, in minimize
    return minimize_dogleg(fun, free_variables=x0, on_step=callback, **options)
`

**Comment by Vova-B** [comment]
These are all parameters that are passed to the function. I have a question, maybe the problem is that I don’t have a value for channels for masks, maybe the mask should be transmitted in a format (width, height, channels)?
![params](https://user-images.githubusercontent.com/35993213/49411203-10d07300-f779-11e8-88cd-23b80b8258d6.PNG)

**Comment by thmoa** [comment]
> `line 66, in rays_from_points points3d = camera.unproject_points(points)`

Check if there are points to unproject.

**Comment by Vova-B** [comment]
Hi! 
It looked like masks, I set them in a format (height, width, 3), when I changed them to (height, width, 1) the problem disappeared.

**Comment by Myzhencai** [comment]
@Vova-B I have meet the same error it seems mine masks turn to 0 when I used the masks2hdf5.py ,can you share the exact way you have used to help me out ? Thanks ,have a nice day ! :-).
