### ISSUE TITLE
Why are you minimizing the minus of joint locations?

### ISSUE THREAD

**Issue by fengyang0317** [thmoa/videoavatars#2]
In keep it smpl paper [7], the authors minimize Geman-McClure penalty function.
Why are you just minimizing the minus of joint locations in https://github.com/thmoa/videoavatars/blob/master/step1_pose.py#L284.

**Comment by shanYanGuan** [comment]
'f.J_proj' is projected keypoints, and f.keypoints was resized keypoints. But I cant understand why it multiple f.keypoints[:, 2]?
 can you help me?

**Comment by fanner01** [comment]
> 
> 
> 'f.J_proj' is projected keypoints, and f.keypoints was resized keypoints. But I cant understand why it multiple f.keypoints[:, 2]?
> can you help me?

f.keypoints[:, 2] is the confidence for each keypoint
