### ISSUE TITLE
Hi! Could you open the shape from shadding implementation for your work ? 

### ISSUE THREAD

**Issue by Vova-B** [thmoa/videoavatars#23]
I'm a student. I have studied your work and tried to do what would the final model was more realistic. I tried to use the algorithm for shape from shading model, which is obtained in step 2, unfortunately I get very low accuracy. Have you written that you used this algorithm and judging from the pictures quite successfully. I would therefore like to ask you for an example implementation of shape from shading for your work. Thanks

**Comment by thmoa** [comment]
I am sorry but we are currently not planning to release the code for "Detailed Human Avatars from Monocular Video" due to time constraints.
