### ISSUE TITLE
How to rig the body model with pose constraints?

### ISSUE THREAD

**Issue by wswdx** [thmoa/videoavatars#24]
As mentioned in the paper, the model can be rigged with a kinematic skeleton enabling approximate pose-dependent surface deformation. But it seems that this part is not implemented in the provided code. How can I change the pose of the body model with my own pose constraints? Any help will be appreciated. Thank u very much!

**Comment by thmoa** [comment]
This question is about SMPL and not this work. Please refer to the paper "SMPL: A Skinned Multi-Person Linear Model".

**Comment by dhruvshah1214** [comment]
@wswdx did you ever figure out how to do this? Trying to do the same thing...

**Comment by A7ocin** [comment]
I'm interested as well. Did someone figure this out?
