### ISSUE TITLE
could you explain more specificly about how you get masks?

### ISSUE THREAD

**Issue by ChenDRAG** [thmoa/videoavatars#31]
> Therefore,  we adopt the CNN based video segmentation method of [9] and train it with 3-4 manual segmentations per sequence. 

Could you explain more specificly ? I'm currently having trouble testing my own data and cannot create good masks.Thanks a lot.
Also,could you please share the model that you have trained?

**Comment by naren142** [comment]
You can use any of the mask generating algorithms like the one mentioned in paper(OSVOS) or MaskRCNN

**Comment by ChenDRAG** [comment]
> We train it with 3-4 manual segmentations per sequence.
I don't quite understand this in your paper?Did you train the network yourself using manually marked dataset? Could you please go into more details?
Thanks.

**Comment by naren142** [comment]
Yeah you need at least one image and it's mask for every sequence to train the network mentioned in the paper(OSVOS) and then you can use some checkpoint to get the results for the remaining images.So, you need to create masks for some images with your own data(at least 1).

**Comment by mukundhan3** [comment]
@naren142 @thmoa  hi, i went through the paper and the code. was able to set it up. i also understand how to run Mask RCNN and get masks for each frame. But what's not clear is how and in what format are the inputs to be provided to get the s/w working? I have also used openPose before. Just need a few pointers on this, if you have got it setup correctly and working. Any quick responses/help would be greatly appreciated. thanks in advance!
