### ISSUE TITLE
Step2 saves beta from Step1.

### ISSUE THREAD

**Issue by firstmover** [thmoa/videoavatars#36]
Hi Thmoa,
Thanks for sharing your code.
When I was running step2_consensus.py, I found the beta saved here

https://github.com/thmoa/videoavatars/blob/791282c5c88a013dfa80231f73b0dd71dbdada15/step2_consensus.py#L135-L139

has the exact same value as beta from step1. Are you doing this intentionally?

Your paper says beta would be optimized in step2. If you are saving a new beta from step2, I guess it should be a different beta from step1. 

I found this problem by comparing pose_data['betas'] and base_smpl.betas.r after line 151. They have the same value. 

I would appreciate it if you can help me with this problem. 

Thanks

**Comment by thmoa** [comment]
Hi firstmover, the offsets are regularized to be close to the beta space. See:

https://github.com/thmoa/videoavatars/blob/791282c5c88a013dfa80231f73b0dd71dbdada15/step2_consensus.py#L72-L77

This way we have only one driving force: the offsets. You could afterward disentangle betas and offsets.

**Comment by firstmover** [comment]
Hi Thmoa,
But the code here 
https://github.com/thmoa/videoavatars/blob/791282c5c88a013dfa80231f73b0dd71dbdada15/step2_consensus.py#L84-L90
shows that step2 optimizes both beta and the offsets. Do you mean step2 does not produce a better beta than step1?
Is it possible to optimize only on betas and exclude offsets in step2?
Thanks

**Comment by firstmover** [comment]
Thanks for your reply. If we are optimizing beta in model_template, isn't it better to save beta in model_template instead of that in base_smpl?

**Comment by fengyang0317** [comment]
Hi Thiemo. Could you give some hints about how to disentangle betas and offsets? Thanks.

> Hi firstmover, the offsets are regularized to be close to the beta space. See:
> 
> https://github.com/thmoa/videoavatars/blob/791282c5c88a013dfa80231f73b0dd71dbdada15/step2_consensus.py#L72-L77
> 
> This way we have only one driving force: the offsets. You could afterward disentangle betas and offsets.

**Comment by bimsarapathiraja** [comment]
Can somebody please explain how offsets generation is achieved?
