### ISSUE TITLE
People snapshot dataset

### ISSUE THREAD

**Issue by yyf8989** [thmoa/videoavatars#42]
- [x] I have read the paper **Video based reconstruction of 3D people models**.
- [x] I have read the license.
- [x] I understand that the authors are under no obligation to reply to comprehension questions regarding the paper or the provided code.
- [x] The issue occurs in the provided code and not in third-party libraries (SMPL, chumpy, OpenDR, ...)

I passed the request for the datasets, but havn't got the reply, how long will the owner reply ?
I would like to use this model to see the paper's result, thanks in advance~

**Comment by yyf8989** [comment]
@thmoa

**Comment by thmoa** [comment]
We only process requests with legible affiliation or proper description of usage.
