### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by FrazierLei** [thmoa/videoavatars#44]
Hi, when runing step_one.py, I got this error:
5.74e+05 | init_pose_0: 5.74e+05
1.30e+05 | init_pose_0: 1.30e+05
4.61e+03 | init_pose_0: 4.61e+03
5.41e+01 | init_pose_0: 5.41e+01
1.23e+01 | init_pose_0: 1.23e+01
1.20e+01 | init_pose_0: 1.20e+01
1.20e+01 | init_pose_0: 1.20e+01
3.17e+05 | init_pose_1: 3.17e+05
7.58e+04 | init_pose_1: 7.58e+04
8.88e+03 | init_pose_1: 8.88e+03
2.84e+03 | init_pose_1: 2.84e+03
1.41e+03 | init_pose_1: 1.41e+03
4.59e+01 | init_pose_1: 4.59e+01
2.58e+01 | init_pose_1: 2.58e+01
2.56e+01 | init_pose_1: 2.56e+01
5.68e+05 | init_pose_2: 5.68e+05
1.65e+05 | init_pose_2: 1.65e+05
2.50e+04 | init_pose_2: 2.50e+04
8.24e+03 | init_pose_2: 8.24e+03
1.69e+03 | init_pose_2: 1.69e+03
2.03e+02 | init_pose_2: 2.03e+02
9.62e+00 | init_pose_2: 9.62e+00
9.00e+00 | init_pose_2: 9.00e+00
9.00e+00 | init_pose_2: 9.00e+00
5.32e+05 | init_pose_3: 5.32e+05
1.30e+05 | init_pose_3: 1.30e+05
1.65e+04 | init_pose_3: 1.65e+04
5.37e+03 | init_pose_3: 5.37e+03
5.77e+02 | init_pose_3: 5.77e+02
3.44e+01 | init_pose_3: 3.44e+01
2.57e+01 | init_pose_3: 2.57e+01
2.57e+01 | init_pose_3: 2.57e+01
1.05e+04 | betas: 0.00e+00 | pose_0: 3.36e+03 | pose_1: 2.77e+03 | pose_2: 2.79e+03 | pose_3: 1.62e+03 | prior_0: 0.00e+00 | prior_1: 0.00e+00 | prior_2: 0.00e+00 | prior_3: 0.00e+00
2.40e+03 | betas: 8.16e+01 | pose_0: 2.77e+02 | pose_1: 7.75e+02 | pose_2: 2.97e+02 | pose_3: 3.72e+02 | prior_0: 2.76e+02 | prior_1: 1.27e+02 | prior_2: 8.50e+01 | prior_3: 1.12e+02
1.91e+03 | betas: 5.45e+01 | pose_0: 2.31e+02 | pose_1: 4.69e+02 | pose_2: 2.46e+02 | pose_3: 3.26e+02 | prior_0: 2.58e+02 | prior_1: 1.10e+02 | prior_2: 8.68e+01 | prior_3: 1.25e+02
1.90e+03 | betas: 5.48e+01 | pose_0: 2.28e+02 | pose_1: 4.59e+02 | pose_2: 2.44e+02 | pose_3: 3.22e+02 | prior_0: 2.61e+02 | prior_1: 1.16e+02 | prior_2: 8.85e+01 | prior_3: 1.28e+02
1.77e+03 | betas: 3.51e+01 | pose_0: 2.28e+02 | pose_1: 4.59e+02 | pose_2: 2.44e+02 | pose_3: 3.22e+02 | prior_0: 2.11e+02 | prior_1: 9.43e+01 | prior_2: 7.17e+01 | prior_3: 1.03e+02
1.75e+03 | betas: 6.32e+01 | pose_0: 1.96e+02 | pose_1: 4.23e+02 | pose_2: 2.26e+02 | pose_3: 2.86e+02 | prior_0: 2.26e+02 | prior_1: 1.13e+02 | prior_2: 8.69e+01 | prior_3: 1.32e+02
1.61e+03 | betas: 3.56e+01 | pose_0: 1.96e+02 | pose_1: 4.23e+02 | pose_2: 2.26e+02 | pose_3: 2.86e+02 | prior_0: 1.78e+02 | prior_1: 8.95e+01 | prior_2: 6.87e+01 | prior_3: 1.04e+02
1.58e+03 | betas: 7.72e+01 | pose_0: 1.62e+02 | pose_1: 3.75e+02 | pose_2: 2.07e+02 | pose_3: 2.46e+02 | prior_0: 1.85e+02 | prior_1: 1.11e+02 | prior_2: 8.46e+01 | prior_3: 1.34e+02
1.58e+03 | betas: 8.56e+01 | pose_0: 1.59e+02 | pose_1: 3.71e+02 | pose_2: 2.07e+02 | pose_3: 2.45e+02 | prior_0: 1.84e+02 | prior_1: 1.12e+02 | prior_2: 8.44e+01 | prior_3: 1.33e+02
Traceback (most recent call last):
  File "step1_pose.py", line 377, in <module>
    args.body_height, args.nohands, args.display)
  File "step1_pose.py", line 319, in main
    fit_pose(current_frame, last_smpl, frustum, nohands, debug_rn)
  File "step1_pose.py", line 197, in fit_pose
    bgcolor=0, num_channels=1)
  File "/usr/local/lib/python2.7/dist-packages/chumpy/ch.py", line 129, in __new__
    result.set(**defs)
  File "/usr/local/lib/python2.7/dist-packages/chumpy/ch.py", line 482, in set
    self.__setattr__(kwall[-1], kwargs[kwall[-1]], None)
  File "/usr/local/lib/python2.7/dist-packages/chumpy/ch.py", line 407, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Looks similar to  https://github.com/thmoa/videoavatars/issues/37, but my machine is ubuntu16.04
So I need your help, thx!

**Comment by FrazierLei** [comment]
I changed chumpy version from 0.68 to 0.67, and got the same result

**Comment by quyanqiu** [comment]
Hey,I got the same problem both in centos7 and windows, actually chumpy and opendr can be running successfully because several project using chumpy and opendr can be running successfully both on linux and windows 7 from my test,have you solved this problem?

**Comment by ranaosama27** [comment]
Is you found solve for this problem ?

**Comment by zhanghongyong123456** [comment]
i have same problem，how to do，you have solve it ？

**Comment by CongSuxu** [comment]
> 

have you solve this poblem?
