### ISSUE TITLE
about mask and camera.pkl

### ISSUE THREAD

**Issue by ischansgithub** [thmoa/videoavatars#45]
Why is the length and width of the camera. pkl file 1080 * 1080, while in fact the video in the data set you provide is 640 * 640, similarly, why is the length and width ratio of the mask you use 1080 * 1080?

Looking forward to your answer，much appreciated!

**Comment by ujjawalcse** [comment]
Hey @ischansgithub ,
Did you get the solution?
Can you please share here?
Thanks.
