### ISSUE TITLE
Smpl texture

### ISSUE THREAD

**Issue by Chromium97** [thmoa/videoavatars#46]
- [x] I have read the paper **Video based reconstruction of 3D people models**.
- [x] I have read the license.
- [x] I understand that the authors are under no obligation to reply to comprehension questions regarding the paper or the provided code.
- [x] The issue occurs in the provided code and not in third-party libraries (SMPL, chumpy, OpenDR, ...)

I saw that your code is the first one to provide texture map for SMPL models.
I had few doubts, no mention of vt or ft is given in paper.
If we see surreal dataset, there texture file is very different from the texture files you have provided.
How to calculate vt or ft?
How to convert surreal dataset texture map to the one provided in videoavatars?

![grey_male_0013](https://user-images.githubusercontent.com/13464149/61030677-84a3bf80-a3db-11e9-8008-05e2e91d5206.jpg)

![sample_texture_2](https://user-images.githubusercontent.com/13464149/61030651-735ab300-a3db-11e9-8e7e-a65bbab94dd3.jpg)

Any help or info will be great.

**Comment by thmoa** [comment]
It is the same texture layout just with inpainted islands.

**Comment by Chromium97** [comment]
could you point me towards converting 1st to 2nd?
