### ISSUE TITLE
Information Required

### ISSUE THREAD

**Issue by mukundhan3** [thmoa/videoavatars#48]
@naren142 @thmoa hi, i went through the paper and the code. was able to set it up. i also understand how to run Mask RCNN and get masks for each frame. But what's not clear is how and in what format are the inputs to be provided to get the s/w working? I have also used openPose before. Just need a few pointers on this, if you have got it setup correctly and working. Any quick responses/help would be greatly appreciated. thanks in advance

**Comment by thmoa** [comment]
check out the demo
