### ISSUE TITLE
can't download dataset from https://graphics.tu-bs.de/people-snapshot

### ISSUE THREAD

**Issue by wangniancai** [thmoa/videoavatars#55]

**Comment by thmoa** [comment]
I have answered this multiple times.

You need to request access. If you have so and you received no answer this means:

you did not submit the required information OR
you did not accept the license OR
your usage is not compatible with the license OR
your mail was not received

**Comment by hzc1997** [comment]
Hello, I want to know which email should I send the request to? What is the email number to send the request?
Can you tell me? Thanks
