### ISSUE TITLE
download the dataset

### ISSUE THREAD

**Issue by hzc1997** [thmoa/videoavatars#56]
Hi,
First of all, thank you for your great work. I want to download the dataset. Could you please tell me which mailbox I should send the request to to get the dataset?Can you tell me your email account number? 
  thank you! looking for your reply!

**Comment by thmoa** [comment]
All information are available here...
https://github.com/thmoa/videoavatars#dataset

**Comment by hzc1997** [comment]
Sorry, I didn't find the email number in the link
