### ISSUE TITLE
Some Questions about Dataset

### ISSUE THREAD

**Issue by ShaofengZou** [thmoa/videoavatars#59]
- [ ] I have read the paper **Video based reconstruction of 3D people models**.
- [ ] I have read the license.
- [ ] I understand that the authors are under no obligation to reply to comprehension questions regarding the paper or the provided code.
- [ ] The issue occurs in the provided code and not in third-party libraries (SMPL, chumpy, OpenDR, ...)

Hey, I am interested in your fatastic work and want to have some application based on your work. 

However, I have encountered problems with the dataset. I am in China and can access google through SSR. 

But the website https://graphics.tu-bs.de/people-snapshot cannot be assessed. It cannot be opened, and I have asked many friends to help me try, but they cannot be opened too. 

So I want to ask how to obtain the dataset through other methods. 

Looking forward to your reply.
Thank you.

**Comment by thmoa** [comment]
Sorry are not able to provide a mirror due to legal constraints.
