### ISSUE TITLE
can not download the dataset from https://graphics.tu-bs.de/people-snapshot

### ISSUE THREAD

**Issue by 17853829** [thmoa/videoavatars#6]
the web site is unavailable.Is there some new site to download the dataset file ?
thanks a lot!

**Comment by thmoa** [comment]
see #5 and #4 

should be back now

**Comment by anphunl** [comment]
It's down again now.

**Comment by BobbiKim** [comment]
Can't download the dataset agian,who can send the data,if you have already downloaded.

**Comment by thmoa** [comment]
The dataset can't be redistributed! Apply for the dataset under https://graphics.tu-bs.de/people-snapshot

**Comment by wangniancai** [comment]
still can't download now
