### ISSUE TITLE
Is the dataset avaliable for research purpose ? I cannot acess the link in the readme.

### ISSUE THREAD

**Issue by maoyali** [thmoa/videoavatars#60]
- [x] I have read the paper **Video based reconstruction of 3D people models**.
- [x] I have read the license.
- [x] I understand that the authors are under no obligation to reply to comprehension questions regarding the paper or the provided code.
- [x] The issue occurs in the provided code and not in third-party libraries (SMPL, chumpy, OpenDR, ...)

Thanks for your code! It's a pity that I cannot acess the dataset's link. Would you please send me one dataset in an email just for a test. Looking forward to your reply~

**Comment by thmoa** [comment]
As in #59: We are not able to provide a mirror due to legal constraints and the dataset is too large to be distributed via email.

The website is up and running... We are not responsible for the GFW....
