### ISSUE TITLE
The following problem occurs when converting json to hdf5 by running 2djointstohdf5.py

### ISSUE THREAD

**Issue by zhumorui** [thmoa/videoavatars#66]
- [x] I have read the paper **Video based reconstruction of 3D people models**.
- [x] I have read the license.
- [x] I understand that the authors are under no obligation to reply to comprehension questions regarding the paper or the provided code.
- [x] The issue occurs in the provided code and not in third-party libraries (SMPL, chumpy, OpenDR, ...)
I got 2djonints from openpose.when I was converting json to hdf5 by running 2djointstohdf5.py,I got this errors.
Can you give me some suggestions to solve this porblems? Thank you very much!

 0% 0/472 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "2djoints2hdf5.py", line 36, in <module>
    poses_dset[i] = pose
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/dataset.py", line 707, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/selections.py", line 299, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, self.mshape))
TypeError: Can't broadcast (75,) -> (54,)

**Comment by thmoa** [comment]
The error is in your qute.

> TypeError: Can't broadcast (75,) -> (54,)

You try to write 75 values in an array of 54.

Please do not open tickets for problems you can debug yourself! If something is wrong in the code, you are welcome to open a PR.

**Comment by zhumorui** [comment]
> 错误在您的报价中。
> 
> > TypeError：无法广播（75，）->（54，）
> 
> 您尝试在54个数组中写入75个值。我猜您正在使用其他联合排序。该项目使用COCO。
> 
> 如果您可以调试自己的问题，请不要打开票证！如果代码中有错误，欢迎您打开PR。

Thank you very much for your help. When I ran mask2hdf5.py, I found a small error. You should use src or src_folder in two different places at the same time.

parser.add_argument('src_folder', type=str)<======
parser.add_argument('target', type=str)

args = parser.parse_args()

out_file = args.target
mask_dir = args.src<======

**Comment by zhumorui** [comment]
> The error is in your quote.
> 
> > TypeError: Can't broadcast (75,) -> (54,)
> 
> You try to write 75 values in an array of 54. My guess is you are using another joint ordering. This project uses COCO.
> 
> Please do not open tickets for problems you can debug yourself! If something is wrong in the code, you are welcome to open a PR.

Thank you very much for your help. When I ran mask2hdf5.py, I found a small error. You should use src or src_folder in two different places at the same time.

parser.add_argument('src_folder', type=str)<======
parser.add_argument('target', type=str)

args = parser.parse_args()

out_file = args.target
mask_dir = args.src<======

**Comment by thmoa** [comment]
thanks. next time please open a PR.
