### ISSUE TITLE
What does texels mean?

### ISSUE THREAD

**Issue by rubilin** [thmoa/videoavatars#67]
I'm sorry to bother you.the article says:"To create the texture, we warp our estimate canonical model back To each frame, back-project the image color To all visible vertices,And finally generate a texture image by calculating the median of the most orthogonal texels from all views". I saw your code, and alpha into to iso_vis.render(alpha), I don't know what is the meaning of this texels.it is on the texture image pixels?or other means.Looking forward to your reply. Thank you very much. Thank you very much.

**Comment by thmoa** [comment]
https://en.wikipedia.org/wiki/Texel_(graphics)
