### ISSUE TITLE
slow

### ISSUE THREAD

**Issue by zhulei1228** [thmoa/videoavatars#68]
Why the step1 is  so slow?when I run it,generating one frame needs 6 minutes.How long does it usually need?

**Comment by rubilin** [comment]
Hello, may I ask if you have run the third step to generate texture images? It is said in the paper that finally generate a texture image by calculating the median of the most orthogonal texels from all views.What is the meaning of texels?What nationality are you? I want to communicate with you

**Comment by zhumorui** [comment]
> Why the step1 is so slow?when I run it,generating one frame needs 6 minutes.How long does it usually need?

The 472 frames cost me 16 hours to run step1.

**Comment by thmoa** [comment]
You do not need to run it for 472 frames - 120 frames are enough (full circe, take every other frame or so). For us it tool 1 min per frame as reported in the paper.
