### ISSUE TITLE
Could you please optimize it and use the configuration file to set it?

### ISSUE THREAD

**Issue by 60999** [thmoa/videoavatars#69]
Could you please optimize it and use the configuration file to set it?
'ln -s <path to smpl folder>/models .
ln -s <path to smpl folder>/smpl_webuser/*.py .'
and 
'cp <path to your smplify installation>/code/lib/sphere_collisions.py .
# these files can be linked
ln -s <path to smplify folder>/code/lib/capsule_body.py .
ln -s <path to smplify folder>/code/lib/capsule_ch.py .
ln -s <path to smplify folder>/code/lib/robustifiers.py .'

In addition, is there any plan to upgrade the code? Now two years have passed and there are many changes.

**Comment by thmoa** [comment]
The project is more than 2 years old and will not be updated.
