### ISSUE TITLE
Time of a complete run

### ISSUE THREAD

**Issue by vladsterz** [thmoa/videoavatars#7]
Hello again, 
so I've received the dataset and I am trying it out. So far I've been running step1 for about 6 hours with female-1-causual set. Is this normal or am I doing something fundamentally wrong? What is the estimated time for a complete run.
Thanks in advance,
Vlad

**Comment by thmoa** [comment]
Step 1 is slow. 6 hours sounds a bit too slow. Please refer to the supplementary material for our timings. However, the dataset gives you pre-computed values. You can also replace step 1 with more recent (CNN-based one-shot) methods.
