### ISSUE TITLE
A pose

### ISSUE THREAD

**Issue by zhulei1228** [thmoa/videoavatars#71]
How to get 3d human avatars of  the corresponding frames ?

**Comment by su-zhuo** [comment]
how do you download the dataset?

**Comment by thmoa** [comment]
See `Readme.md`.

**Comment by decajcd** [comment]
> See `Readme.md`.
Not mentioned in `Readme.md`

**Comment by decajcd** [comment]
> See `Readme.md`.

Not mentioned in Readme.md

**Comment by decajcd** [comment]
> See `Readme.md`.

No mentioned in Readme.md
