### ISSUE TITLE
Could you disclose which device was used to capture the dataset, or the intrinsic parameters (sensor width or focal length)?

### ISSUE THREAD

**Issue by aashutosh1997** [thmoa/videoavatars#73]
- [x] I have read the paper **Video based reconstruction of 3D people models**.
- [x] I have read the license.
- [x] I understand that the authors are under no obligation to reply to comprehension questions regarding the paper or the provided code.
- [ ] The issue occurs in the provided code and not in third-party libraries (SMPL, chumpy, OpenDR, ...)

I'm trying to optimize the reconstruction further. Thanks!

**Comment by thmoa** [comment]
The intrinsics of the camera are included in the dataset (`camera.pkl`).
