### ISSUE TITLE
can't open dataset link. Is there other way? 

### ISSUE THREAD

**Issue by lizhongyu3** [thmoa/videoavatars#74]
- [✅ ] I have read the paper **Video based reconstruction of 3D people models**.
- [✅ ] I have read the license.
- [✅ ] I understand that the authors are under no obligation to reply to comprehension questions regarding the paper or the provided code.
- [✅ ] The issue occurs in the provided code and not in third-party libraries (SMPL, chumpy, OpenDR, ...)

Hello, the dataset website has some problems, I can't open the link. How can I get the dataset ? Thantk you

**Comment by thmoa** [comment]
No other way sorry. Sometimes the website is in maintenance. If so please try again later.
