### ISSUE TITLE
I want to change the pose,not "T" pose,what should I do ?

### ISSUE THREAD

**Issue by lizhongyu3** [thmoa/videoavatars#77]
- [√] I have read the paper **Video based reconstruction of 3D people models**.
- [√ ] I have read the license.
- [√ ] I understand that the authors are under no obligation to reply to comprehension questions regarding the paper or the provided code.
- [ √] The issue occurs in the provided code and not in third-party libraries (SMPL, chumpy, OpenDR, ...)

thank you !! just for study and research~!

**Comment by thmoa** [comment]
learn about SMPL
