### ISSUE TITLE
Frame number difference in reconstructed_poses.hdf5 vs masks.hdf5

### ISSUE THREAD

**Issue by sxyu** [thmoa/videoavatars#78]
Hi,
In your people-snapshot dataset, the recovered poses `reconstructed_poses.hdf5` seem to have one extra frame as compared `masks.hdf5` and the video. For example, male-1-casual has 834 video frames but 835 poses.
I'm wondering why this is the case.

**Comment by thmoa** [comment]
No idea - is this a problem? Sorry this is 3 year old code...

**Comment by sxyu** [comment]
it's unclear how to match your predicted human to the video if the frames numbers are different.
I suppose I can just remove the last frame, but wanted to ask in case you knew something.
