### ISSUE TITLE
Sample run commands are greatly appreciated

### ISSUE THREAD

**Issue by pranavvaidik** [thmoa/videoavatars#79]
- [* ] I have read the paper **Video based reconstruction of 3D people models**.
- [ *] I have read the license.
- [ *] I understand that the authors are under no obligation to reply to comprehension questions regarding the paper or the provided code.
- [ *] The issue occurs in the provided code and not in third-party libraries (SMPL, chumpy, OpenDR, ...)

Hi,

I am trying to run the Step1_pose.py code and found that a lot of argument issues arise. I was looking for some example commands to run, with some default files I can use it on. Can I please get some example commands so I can test if my installation is done correctly? I don't know the extensions for a lot of the files the argparse commands are looking for in the code. I am sure that similar problems will persist for other steps as well. May I suggest expanding the readme file to include these instructions?

Thanks,
Pranav

**Comment by thmoa** [comment]
The dataset includes all you need.

**Comment by shlokshah** [comment]
Hi Pranav,
I am working on this project as well. I've formulated a few commands are going through the code and the data:
(people_snapshot_public is the name of the data folder)
STEP 1 - Pose estimation

Input: 1. Keypoints.hdf5 2. masks.hdf5 3. camera.pkl
Output: 1. Reconstructed_poses.hdf5 

python3 step1_pose.py /path/to/people_snapshot_public/male-3-casual/keypoints.hdf5  /path/to/people_snapshot_public/male-3-casual/masks.hdf5 /path/to/people_snapshot_public/male-3-casual/camera.pkl  /path/to/output/directory/reconstructed_poses.hdf5

STEP 2 - Consensus object generation

Input: 1. Reconstructed_poses.hdf5 2. masks.hdf5 3. camera.pkl
Output: 1. consensus.pkl 2. consensus.obj

python3 step2_consensus.py /path/to/output/directory/reconstructed_poses.hdf5 /path/to/people_snapshot_public/male-3-casual/masks.hdf5  /path/to/people_snapshot_public/male-3-casual/camera.pkl /path/to/output/directory/consensus.pkl --obj_out /path/to/output/directory/consensus.obj

STEP 3 - Texture map generation 

Input: 1. consensus.pkl 2. camera.pkl 3. male-3-casual.mp4 (Video input) 4. Reconstructed_poses.hdf5 5. masks.hdf5
Output: 1. tex-male-3-casual.jpg (Texture map)

python3 step3_texture.py /path/to/output/directory/consensus.pkl  /path/to/people_snapshot_public/male-3-casual/camera.pkl  /path/to/people_snapshot_public/male-3-casual/male-3-casual.mp4 /path/to/output/directory/reconstructed_poses.hdf5 /path/to/people_snapshot_public/male-3-casual/masks.hdf5 /path/to/output/directory/tex-male-3-casual.jpg

These commands are providing only the necessary files, fine tuning of parameters can be done too. Would recommend you to read the scripts and the code snippet of the arguments block in them to understand.
