### ISSUE TITLE
Question: How to prepare my own data?

### ISSUE THREAD

**Issue by fz10** [thmoa/videoavatars#82]
- [x] I have read the paper **Video based reconstruction of 3D people models**.
- [x] I have read the license.
- [x] I understand that the authors are under no obligation to reply to comprehension questions regarding the paper or the provided code.
- [x] The issue occurs in the provided code and not in third-party libraries (SMPL, chumpy, OpenDR, ...)

Hello,

I just wanted to know how to properly input my own data. I have filmed myself, and I have reviewed the scripts in prepare_data but in file 2djoints2hdf5.py it asks me to input openpose_detections directory that contains Json files which I don't know how to create them or where to get them from with my specific input.

I would really appreciate an answer to this question so I can input my own data properly. Thanks in advance for your reply!

**Comment by thmoa** [comment]
You need to run the OpenPose detector as described in the paper. Sorry I cannot support this old project any longer.
