### ISSUE TITLE
TypeError: expected bytes, str found

### ISSUE THREAD

**Issue by ljq2020** [thmoa/videoavatars#83]
- [x] I have read the paper **Video based reconstruction of 3D people models**.
- [x] I have read the license.
- [x] I understand that the authors are under no obligation to reply to comprehension questions regarding the paper or the provided code.
- [x] The issue occurs in the provided code and not in third-party libraries (SMPL, chumpy, OpenDR, ...)
Hello,

when I run `step1_pose.py`, I meet an error:
`  File "/home/ubuntu/anaconda3/envs/mykaolin/lib/python3.7/site-packages/opendr/renderer.py", line 820, in _setup_camera
    gl.ShaderSource(vs, 1, vs_source, len(vs_source))
  File "opendr/contexts/ctx_base.pyx", line 24, in opendr.contexts.ctx_mesa.mc.with_make_current
  File "opendr/contexts/ctx_base.pyx", line 464, in opendr.contexts.ctx_mesa.OsContextBase.ShaderSource
TypeError: expected bytes, str found
`
and I found the error is `rn_m * dist_o * 100. + (1 - rn_m) * dist_i`,  I'm confused about the class can arithmetic operations.
`rn_m = ColoredRenderer(camera=frame.camera, v=frame.smpl, f=faces, vc=np.ones_like(frame.smpl), frustum=frustum,
                           bgcolor=0, num_channels=1)

    E = {
        'mask': gaussian_pyramid(rn_m * dist_o * 100. + (1 - rn_m) * dist_i, n_levels=4, normalization='size') * 80.,
        '2dpose': GMOf(frame.pose_obj, 100),
        'prior': frame.pose_prior_obj * 4.,
        'sp': frame.collision_obj * 1e3,
    }`
Thank you in advance

**Comment by ljq2020** [comment]
use python2.7

**Comment by chenrc** [comment]
@ljq2020 
Thank you very much for your answer. 
When I use Python 3, I have the same error as you. But when I use Python 2.7, I can't install dependencies which from "requirement.txt". For example, numpy>=1.11.0 can't be installed when I use Python2.7, which raises RuntimeError: Python version >= 3.7 required.
Thank you in advance and look forward to your reply.
