### ISSUE TITLE
what is pkl file that contains camera settings

### ISSUE THREAD

**Issue by YuanLeung** [thmoa/videoavatars#9]
Can anyone describe the detail of camera settings needed in step1_pose.py ? Thanks.

**Comment by labellson** [comment]
Camera settings are the intrinsic camera matrix. There's a helper script, [create_camera.py](https://github.com/thmoa/videoavatars/blob/master/prepare_data/create_camera.py) that creates the .pkl file with the camera parameters you specify.

**Comment by Superlee506** [comment]
@labellson Hi, do you know the exact meaning of the camera param? If we don't use Camera calibration， how can we get the param?
